name: Build simple Java JAR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Compile Java file
        run: |
          mkdir -p out
          javac -d out hello.java

      - name: Create Manifest file
        run: |
          echo "Main-Class: hello" > manifest.txt
          printf "\n" >> manifest.txt

      - name: Create JAR file
        run: |
          jar cfm hello.jar manifest.txt -C out .

      - name: Upload built jar
        uses: actions/upload-artifact@v4
        with:
          name: hello-jar
          path: hello.jar
